### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FaridHidden** [Imandaneshi/jack-telegram-bot#45]
moon: /usr/local/share/lua/5.1/redis.lua:764: could not connect to 127.0.0.1:6379 [connection refused]
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/redis.lua:802: in function 'error'
        /usr/local/share/lua/5.1/redis.lua:764: in function </usr/local/share/lua/5.1/redis.lua:760>
        (tail call): ?
        /usr/local/share/lua/5.1/redis.lua:836: in function 'connect'
        utilities.moon:10: (15) in function '__init'
        utilities.moon:11: (26) in function 'Redis'
        jackbot.moon:15: (17) in main chunk
what is this error

**Comment by Imandaneshi** [comment]
Your Redis server is crashed or stopped
Enter following command and it start jack again
`sudo service redis-server start`
